import { ArchitectureContract } from '@letsela/core';
import * as fs from 'fs/promises';
import * as path from 'path';

export interface GenerationContext {
  architecture: ArchitectureContract;
  projectId: string;
  sessionId: string;
  outputDir: string;
}

export class FileGeneratorEngine {
  async generateProject(context: GenerationContext): Promise<string> {
    const { architecture, outputDir } = context;
    
    console.log(`[FileGenerator] Writing to ${outputDir}`);
    
    // Create output directory
    await fs.mkdir(outputDir, { recursive: true });
    
    // Generate package.json
    const packageJson = {
      name: context.projectId,
      version: "1.0.0",
      scripts: {
        dev: "next dev",
        build: "next build",
        start: "next start"
      },
      dependencies: {
        next: "^14.0.0",
        react: "^18.2.0",
        "react-dom": "^18.2.0"
      }
    };
    
    await fs.writeFile(
      path.join(outputDir, "package.json"),
      JSON.stringify(packageJson, null, 2)
    );
    
    // Generate a simple page
    const indexPath = path.join(outputDir, "pages");
    await fs.mkdir(indexPath, { recursive: true });
    
    const indexContent = `
export default function Home() {
  return (
    <div style={{ padding: "2rem" }}>
      <h1>${architecture.projectId}</h1>
      <p>Generated by Lets'ela</p>
      <p>Stack: ${architecture.stack.frontend} + ${architecture.stack.backend}</p>
    </div>
  );
}
`;
    
    await fs.writeFile(path.join(indexPath, "index.js"), indexContent);
    
    console.log(`[FileGenerator] Generated ${architecture.dataModel.length} tables, ${architecture.apiEndpoints.length} APIs`);
    
    return outputDir;
  }
}
